baseURL = 'https://evocn.org/'
languageCode = 'en-us'
title = 'evocations'
theme = 'archie'
copyright = "evocations"
googleAnalytics = "G-7W98KDFL8L"
pygmentsstyle = "rrt"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
publishDir = "docs"

[params]
    mode="toggle"
    useCDN=false
	subtitle = "Making games and movies!!!"
	description = "Making games and movies!!!"
	favicon="favicon.png"

[[params.social]]
name = "My Youtube Channel"
icon = "youtube"
url = "https://youtube.com/@alexanderhartford"

[[params.social]]
name = "My GitHub"
icon = "github"
url = "https://github.com/evocn"

[[params.social]]
name = "Email me!"
icon = "mail"
url = "mailto: alexanderhartford@gmail.com"

[[params.social]]
name = "RSS"
icon = "rss"
url = "https://evocn.org/posts/index.xml"

[[menu.main]]
name = "about"
url = "/about"
weight = 1

[[menu.main]]
name = "games"
url = "/games"
weight = 2

[[menu.main]]
name = "films"
url = "/films"
weight = 3

[[menu.main]]
name = "archive"
url = "/posts"
weight = 4

[[menu.main]]
name = "tags"
url = "/tags"
weight = 5

